name: mml-life-plugin
version: 1.0
author: maroskomml
main: sk.maroskomml.lifeplugin.LifePlugin
api-version: 1.17
commands:
  mmlhelp:
    description: Napoveda pre mml life plugin.
    usage: /<command>
    aliases: mmlh
  mmlmylife:
    description: Zobrazi kolko mas zivota..
    usage: /<command>
    aliases: mmlml
  mmllife:
    description: Zobrazi kolko zivota ma hrac.
    usage: /<command> [player]
    aliases: mmll
  mmlgivelife:
    description: Umozni dat svoj zivot inemu hracovi. Nemozes dat viac zivotov nez mas. Pocet musi byt cele cislo vacsie alebo rovne 0.
    usage: /<command> [player] pocet
    aliases: mmlgl
  mmlsetlife:
    description: Nasetuje zivot hracovy. Pocet musi byt cele cislo vacsie alebo rovne 0.
    usage: /<command> [player] pocet
    aliases: mmlsl
    permission: op
    permission-message: Nemas pravo nasetovat zivoty.
  mmlcycleinfo:
    description: Zobrazi informaciu o ozivovacom cykle. Kedy bol naposledy, kedy bude najblyssie a kolko zivotov bude pridanych.
    usage: /<command>
    aliases: mmlci